# Generated by Django 5.0.6 on 2024-06-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(default='', max_length=100)),
                ('member_pw', models.CharField(default='', max_length=100)),
                ('member_nick', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
