# Generated by Django 5.0.6 on 2024-06-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(default='', max_length=100)),
                ('board_title', models.CharField(default='', max_length=200)),
                ('board_content', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
